# ================================
# Application
# ================================
spring.application.name=backend

# ================================
# PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bfdmm_db
spring.datasource.username=bfdmm_user
spring.datasource.password=bfdmm_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# Security - desactivee N1-Silos
# ================================
spring.security.user.name=admin
spring.security.user.password=admin

# ================================
# Serveur
# ================================
server.port=8080

# ================================
# Actuator
# ================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ================================
# Info
# ================================
info.app.name=BFDMM Prototype
info.app.version=1.0.0
info.app.description=Burkina Faso DevSecOps Maturity Model